### ISSUE TITLE
Lack of structure documentation of new site

### ISSUE THREAD

**Issue by Deele** [yiisoft-contrib/yiiframework.com#162]
Seeing current pace of contributions, it seems that there are some sort of issues that cause slowdowns and lack of new contributors joining.

Repository issues is good tool for writing down things that needs to be done, but it lacks general picture and without reading through all the issues, people are not able to understand where this is heading.

From my point of view, except for existing developers that are busy and do not find spare attention resource for new contributions, there could be a problem, that new website project is not properly documented and it is hard to see big picture, zoom in, and contribute one small thing at the time, without sinking deep into whole site and keep context in head that greatly slows down pace of development.

In such documentation, all the pages, all the blocks/widgets should be listed and all the required functions should be noted. Already done and partially finished components should be appropriately marked. Such information would greatly help existing and new contributors get into context of project much faster and have a material for reference when questions arise.

I am willing to contribute work in creating such documentation in format of Wiki section in this repository and I would appreciate any information you, existing contributors, can give, in any (raw) format, that would describe blocks that you are creating or already have created, so that information can be used & converted to mentioned documentation, so that everyone would know in what direction this project is heading.

**Comment by samdark** [comment]
I've enabled wiki. Please check if editing is available to you.

**Comment by samdark** [comment]
https://github.com/yiisoft-contrib/yiiframework.com/issues/94

**Comment by cebe** [comment]
What is currently stopping us from switching the new site is the following:

- [ ] User system
  - [ ] Login is working with the old forum login
  - [ ] We need to find a way (preferrably OAuth to make the forum auto login with the site account)
         This was the other way round before but we want to keep control of the login code.
  - [ ] bage system needs to be ported from the old website (#156)
- [ ] Extensions from old website need to be ported to not throw away content, it should be integrated with the new extension list via packagist. There is no concept for this yet. #15 - I would not make it read-only. This is also related to #19
- [ ] Wiki from old website need to be ported to not throw away content #16 - I would not make it read-only.
- [ ] Decision on whether to replace the forum and with which solution. Currently because of lack of time I'd prefer to keep current forum and release the site first. Then afterwards discuss that topic again and switch forum to a more modern solution. #84

**Comment by Deele** [comment]
[First iteration](https://github.com/yiisoft-contrib/yiiframework.com/wiki/Home/4a8cff88c3f944a5af51fe7a38c801cc2cfd83e9) is done.

There are many consistency issues that is yet to be dealt with. For example, "About" stuff should go into "about" controller, the same for pages related to "Development", "Support" and "Learn", where "Support" section is my attempt to separate support from development.

**Comment by jacmoe** [comment]
About controller? Imo that would be over engineering it.

**Comment by samdark** [comment]
I agree that this particular suggestion sounds like over-engineering.
